Enhance WXPython4 compatibility in Default Profile Reversion dialog
lambda-nvda/lambdaNvda pull request #52
Opened 2018-08-31 22:15 UTC by ivnc

In order to improve compatibility with WXPython 4, deprecated wx.NewId() has been changed to wx.ID_ANY on lambdaSetupProfile, as IDs are not relevant in this case.
In addition, the version in buildVars was updated from 1.2.1A to 1.2.2-dev.

If any problem please comment.

2018-09-01 09:40 UTC, nvdaes requested changes
This ensures compatibility with wx Py 4. Anyway, this dialog could be improved by using guiHelper to enhance the visual appearance, according to NVDA 2016.4 and above.
Also, this could be documented in the readme.

2018-09-01 23:51 UTC, ivnc commented
Now guiHelper is used. Please review it again.
What do you suggest to include in documentation? Changelog usually isn't updated until a stable release preparation.

Regards.

2018-09-02 09:04 UTC, nvdaes approved these changes

2018-09-02 09:13 UTC, nvdaes commented
I approved changes since comments are related just to style, not functionality:
- Generally, sHelper instead of helper is used, but this is optional.
- -1 argument can be removed in the static text control, and wx.ID_ANY is not needed for checkboxes using guiHelper. See the Document formatting dialog in NVDA for an example.
- About documentation, I suggest something like:

* Compatible with NVDA 2018.3 and later.

Thanks

2018-09-02 19:20 UTC, ivnc commented
I implemented your suggestions, so I think we can merge now. Regarding the update of the changelog I think that we can do it when preparing 1.2.2 stable, and anyway directly to master.

Regards.

2018-09-02 19:21 UTC, merged

2018-09-02 19:26 UTC, ivnc commented
By the way, thanks for your comments. I'm new to coding and any help is always appreciated.

Regards.

2018-09-02 19:39 UTC, nvdaes commented
OK, if you need access to addonFiles to update get.php let me know. Joseph and me are admins of addonFiles repo. Or I can modify get.php, but perhaps it's better that people can write to the repo to work faster and we can do other things too.

2018-09-02 19:46 UTC, ivnc commented
I think I already have write access to addonFiles. Anyway I'll check and 
let you know if not.


Thanks. Regards.

2018-09-02 19:49 UTC, nvdaes commented
Yes, I remember I gave access to you, but in case this was lost or something, since a person removed it and then access for people could suffer changes, and I'm not sure when this happened.